import { describe, expect, it } from "vitest";
import {
  type EstateSummaryData,
  type ExportSection,
  formatLabel,
  generateEstateCSV,
} from "../estate-export";

/**
 * Estate Export Utilities Tests
 *
 * Tests CSV generation and formatting utilities for estate summary data.
 * Ensures proper CSV formatting, special character escaping, and
 * correct section rendering.
 */

function makeMinimalData(overrides?: Partial<EstateSummaryData>): EstateSummaryData {
  return {
    activation: {
      _id: "test-id",
      deceasedName: "John Doe",
      status: "active",
      activatedAt: new Date(2024, 0, 15).getTime(),
      ...overrides?.activation,
    },
    executorName: "Jane Doe",
    checklistItems: [],
    assets: [],
    communications: [],
    distributions: [],
    generatedAt: new Date(2024, 5, 1).getTime(),
    ...overrides,
  };
}

describe("formatLabel", () => {
  it("should return category labels for known categories", () => {
    expect(formatLabel("first_things_first")).toBe("First Things First");
    expect(formatLabel("legal_and_financial")).toBe("Legal & Financial");
    expect(formatLabel("property_and_assets")).toBe("Property & Assets");
    expect(formatLabel("notifications")).toBe("Notifications");
    expect(formatLabel("ongoing")).toBe("Ongoing");
    expect(formatLabel("when_ready")).toBe("When Ready");
  });

  it("should return status labels for known statuses", () => {
    expect(formatLabel("identified")).toBe("Identified");
    expect(formatLabel("in_transfer")).toBe("In Transfer");
    expect(formatLabel("completed")).toBe("Completed");
  });

  it("should return method labels for known methods", () => {
    expect(formatLabel("phone")).toBe("Phone");
    expect(formatLabel("email")).toBe("Email");
    expect(formatLabel("in_person")).toBe("In Person");
    expect(formatLabel("wire_transfer")).toBe("Wire Transfer");
  });

  it("should return the input string for unknown keys", () => {
    expect(formatLabel("unknown_key")).toBe("unknown_key");
    expect(formatLabel("something_else")).toBe("something_else");
  });

  it("should return empty string for empty input", () => {
    expect(formatLabel("")).toBe("");
  });
});

describe("generateEstateCSV", () => {
  describe("header section", () => {
    it("should include estate name and executor in the header", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("Estate Summary Report");
      expect(csv).toContain("John Doe");
      expect(csv).toContain("Jane Doe");
    });

    it("should include status in the header", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("Active");
    });

    it("should include date of death when provided", () => {
      const data = makeMinimalData({
        activation: {
          _id: "test-id",
          deceasedName: "John Doe",
          dateOfDeath: new Date(2024, 0, 1).getTime(),
          status: "active",
          activatedAt: new Date(2024, 0, 15).getTime(),
        },
      });
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("Date of Death");
    });

    it("should omit date of death when not provided", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      expect(csv).not.toContain("Date of Death");
    });

    it("should include the disclaimer footer", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("Generated by Pathible - not legal advice");
    });
  });

  describe("checklist section", () => {
    it("should render checklist items when section is included", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: "Get death certificates",
            category: "first_things_first",
            isCompleted: true,
            completedAt: new Date(2024, 1, 1).getTime(),
          },
          {
            title: "Contact attorney",
            category: "first_things_first",
            isCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).toContain("CHECKLIST");
      expect(csv).toContain("Get death certificates");
      expect(csv).toContain("Contact attorney");
      expect(csv).toContain("Complete");
      expect(csv).toContain("Pending");
    });

    it("should skip checklist section when items are empty", () => {
      const data = makeMinimalData({ checklistItems: [] });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).not.toContain("CHECKLIST");
    });

    it("should skip checklist section when not in sections list", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: "Some task",
            category: "first_things_first",
            isCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["assets"]);
      expect(csv).not.toContain("CHECKLIST");
    });

    it("should include notes for checklist items", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: "Task with notes",
            category: "ongoing",
            isCompleted: false,
            notes: "Important note here",
          },
        ],
      });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).toContain("Important note here");
    });
  });

  describe("assets section", () => {
    it("should render assets when section is included", () => {
      const data = makeMinimalData({
        assets: [
          {
            name: "Checking Account",
            category: "financial_account",
            status: "identified",
            estimatedValue: 50000,
            institution: "Big Bank",
          },
        ],
      });
      const csv = generateEstateCSV(data, ["assets"]);
      expect(csv).toContain("ASSETS");
      expect(csv).toContain("Checking Account");
      expect(csv).toContain("Financial Account");
      expect(csv).toContain("Identified");
      expect(csv).toContain("$50,000");
      expect(csv).toContain("Big Bank");
    });

    it("should skip assets section when items are empty", () => {
      const data = makeMinimalData({ assets: [] });
      const csv = generateEstateCSV(data, ["assets"]);
      expect(csv).not.toContain("ASSETS");
    });

    it("should handle assets without optional fields", () => {
      const data = makeMinimalData({
        assets: [
          {
            name: "Mystery Item",
            category: "other",
            status: "identified",
          },
        ],
      });
      const csv = generateEstateCSV(data, ["assets"]);
      expect(csv).toContain("Mystery Item");
      expect(csv).toContain("Other");
    });
  });

  describe("communications section", () => {
    it("should render communications when section is included", () => {
      const data = makeMinimalData({
        communications: [
          {
            recipientName: "Bank Manager",
            recipientOrganization: "Big Bank",
            method: "phone",
            subject: "Account closure",
            summary: "Called to close account",
            category: "financial_institution",
            communicationDate: new Date(2024, 2, 15).getTime(),
          },
        ],
      });
      const csv = generateEstateCSV(data, ["communications"]);
      expect(csv).toContain("COMMUNICATIONS");
      expect(csv).toContain("Bank Manager");
      expect(csv).toContain("Big Bank");
      expect(csv).toContain("Phone");
      expect(csv).toContain("Account closure");
    });

    it("should handle follow-up fields", () => {
      const data = makeMinimalData({
        communications: [
          {
            recipientName: "Attorney",
            method: "email",
            subject: "Follow up",
            summary: "Sent email",
            category: "legal",
            communicationDate: new Date(2024, 2, 1).getTime(),
            followUpDate: new Date(2024, 2, 15).getTime(),
            followUpCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["communications"]);
      expect(csv).toContain("No");
    });

    it("should show Yes for completed follow-ups", () => {
      const data = makeMinimalData({
        communications: [
          {
            recipientName: "Attorney",
            method: "email",
            subject: "Follow up",
            summary: "Sent email",
            category: "legal",
            communicationDate: new Date(2024, 2, 1).getTime(),
            followUpDate: new Date(2024, 2, 15).getTime(),
            followUpCompleted: true,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["communications"]);
      expect(csv).toContain("Yes");
    });
  });

  describe("distributions section", () => {
    it("should render distributions when section is included", () => {
      const data = makeMinimalData({
        distributions: [
          {
            beneficiaryName: "Alice Doe",
            beneficiaryRelationship: "Daughter",
            description: "Family home",
            value: 350000,
            distributionDate: new Date(2024, 6, 1).getTime(),
            method: "title_transfer",
          },
        ],
      });
      const csv = generateEstateCSV(data, ["distributions"]);
      expect(csv).toContain("DISTRIBUTIONS");
      expect(csv).toContain("Alice Doe");
      expect(csv).toContain("Daughter");
      expect(csv).toContain("Family home");
      expect(csv).toContain("$350,000");
      expect(csv).toContain("Title Transfer");
    });

    it("should skip distributions section when items are empty", () => {
      const data = makeMinimalData({ distributions: [] });
      const csv = generateEstateCSV(data, ["distributions"]);
      expect(csv).not.toContain("DISTRIBUTIONS");
    });
  });

  describe("multiple sections", () => {
    it("should render all requested sections", () => {
      const data = makeMinimalData({
        checklistItems: [{ title: "Task 1", category: "ongoing", isCompleted: false }],
        assets: [{ name: "Asset 1", category: "other", status: "identified" }],
        communications: [
          {
            recipientName: "Contact 1",
            method: "phone",
            subject: "Inquiry",
            summary: "Called",
            category: "other",
            communicationDate: new Date(2024, 3, 1).getTime(),
          },
        ],
        distributions: [
          {
            beneficiaryName: "Heir 1",
            distributionDate: new Date(2024, 6, 1).getTime(),
            method: "check",
          },
        ],
      });
      const sections: ExportSection[] = ["checklist", "assets", "communications", "distributions"];
      const csv = generateEstateCSV(data, sections);
      expect(csv).toContain("CHECKLIST");
      expect(csv).toContain("ASSETS");
      expect(csv).toContain("COMMUNICATIONS");
      expect(csv).toContain("DISTRIBUTIONS");
    });
  });

  describe("CSV formatting", () => {
    it("should escape commas in field values", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: "Contact banks, brokerages, and institutions",
            category: "legal_and_financial",
            isCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).toContain('"Contact banks, brokerages, and institutions"');
    });

    it("should escape double quotes in field values", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: 'Review the "final" documents',
            category: "legal_and_financial",
            isCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).toContain('"Review the ""final"" documents"');
    });

    it("should escape newlines in field values", () => {
      const data = makeMinimalData({
        checklistItems: [
          {
            title: "Line one\nLine two",
            category: "ongoing",
            isCompleted: false,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["checklist"]);
      expect(csv).toContain('"Line one\nLine two"');
    });

    it("should produce lines separated by newlines", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      const lines = csv.split("\n");
      expect(lines.length).toBeGreaterThan(1);
    });

    it("should not have trailing comma on rows", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      const lines = csv.split("\n").filter((l) => l.length > 0);
      for (const line of lines) {
        expect(line.endsWith(",")).toBe(false);
      }
    });
  });

  describe("edge cases", () => {
    it("should handle empty sections list", () => {
      const data = makeMinimalData();
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("Estate Summary Report");
      expect(csv).toContain("Generated by Pathible");
      expect(csv).not.toContain("CHECKLIST");
      expect(csv).not.toContain("ASSETS");
    });

    it("should handle special characters in names", () => {
      const data = makeMinimalData({
        activation: {
          _id: "test-id",
          deceasedName: "O'Brien, Mary-Jane",
          status: "active",
          activatedAt: new Date(2024, 0, 15).getTime(),
        },
        executorName: 'Smith "Jr." III',
      });
      const csv = generateEstateCSV(data, []);
      expect(csv).toContain("O'Brien");
      expect(csv).toContain("Smith");
    });

    it("should handle zero-value assets", () => {
      const data = makeMinimalData({
        assets: [
          {
            name: "Closed Account",
            category: "financial_account",
            status: "closed",
            estimatedValue: 0,
          },
        ],
      });
      const csv = generateEstateCSV(data, ["assets"]);
      expect(csv).toContain("$0");
    });
  });
});
